# Generated by Django 5.2.8 on 2025-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterUsers', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=20),
        ),
    ]
