# Generated by Django 5.2.8 on 2025-11-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidatePosts', '0002_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Separar con comas (ej: deportes, ciencia, colegio)', max_length=255),
        ),
    ]
