# Generated by Django 5.2.8 on 2025-11-25 17:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidatePosts', '0004_post_attachment_post_links_post_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
