"""
Django settings for postingcollage project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import cloudinary
import cloudinary.uploader
import cloudinary.api
import os
import dj_database_url
from dotenv import load_dotenv

# Cargar variables de entorno del archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', default='your secret key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Publicates',
    'RegisterUsers',
    'ValidatePosts',
    'django_ckeditor_5',
    'cloudinary',
    'cloudinary_storage',
]

AUTH_USER_MODEL = "RegisterUsers.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'postingcollage.middleware.ErrorLoggingMiddleware',
]


ROOT_URLCONF = 'postingcollage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'Publicates' / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'postingcollage.wsgi.application'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Estas fuerzan el uso de cookies seguras, lo cual es vital
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    "https://aquileoparra-periodico-escolar.onrender.com", 
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:postgres@localhost/postgres',
        conn_max_age=600
    )
}

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "strikethrough",
            "subscript", "superscript", "|",
            "bulletedList", "numberedList", "|",
            "link", "imageUpload", "mediaEmbed", "|",
            "undo", "redo",
        ],
        "image_backend": "cloudinary",
        "upload_path": "posts/",
    }
}


CKEDITOR_5_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "any"


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_ALLOW_NONIMAGE_FILES = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "xazadox@gmail.com"
EMAIL_HOST_PASSWORD = "zhvh fave ipcg bweo"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Cloudinary (REQUIERE `CLOUDINARY_URL` en producción)
# Use una sola variable de entorno con el formato:
#   CLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<cloud_name>
#
# NOTA: cloudinary.config() debe ser invocado explícitamente con los parámetros
# parseados desde CLOUDINARY_URL para asegurar que están disponibles en settings.py
# (no se puede confiar en que el auto-config ocurra antes).

def _parse_cloudinary_url():
    """Parse CLOUDINARY_URL from environment and return (cloud_name, api_key, api_secret) or (None, None, None)."""
    cloudinary_url = os.environ.get("CLOUDINARY_URL", "")
    if not cloudinary_url.startswith("cloudinary://"):
        return None, None, None
    # Formato: cloudinary://api_key:api_secret@cloud_name
    try:
        # Remover prefijo
        url_part = cloudinary_url.replace("cloudinary://", "", 1)
        # Dividir en credenciales y cloud_name
        creds_part, cn = url_part.rsplit("@", 1)
        ak, as_ = creds_part.split(":", 1)
        return cn, ak, as_
    except (ValueError, AttributeError):
        return None, None, None


CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL")

# Forzar uso de CLOUDINARY_URL cuando DEBUG=False (producción)
if CLOUDINARY_URL:
    cloud_name, api_key, api_secret = _parse_cloudinary_url()
    if cloud_name and api_key and api_secret:
        # Configurar cloudinary explícitamente con los valores parseados
        cloudinary.config(
            cloud_name=cloud_name,
            api_key=api_key,
            api_secret=api_secret,
            secure=True
        )
        DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
        try:
            cfg = cloudinary.config()
            # No imprimimos secretos; mostramos solo lo necesario para depuración
            masked_key = (cfg.api_key[:4] + '...' + cfg.api_key[-4:]) if cfg.api_key else 'None'
            CLOUDINARY_STORAGE = {
                'CLOUD_NAME': cfg.cloud_name,
                'API_KEY': cfg.api_key,
                'API_SECRET': '***MASKED***',
                'SECURE': True,
            }
            # Poner MEDIA_URL al CDN de Cloudinary para que CKEditor y templates apunten al CDN
            try:
                MEDIA_URL = f"https://res.cloudinary.com/{cfg.cloud_name}/"
                CLOUDINARY_STORAGE['MEDIA_URL'] = MEDIA_URL
            except (ValueError, AttributeError, TypeError):
                MEDIA_URL = '/media/'
            # Prints de diagnóstico (NO exponen el api_secret) - solo en DEBUG o si VERBOSE_STARTUP=1
            if DEBUG or os.environ.get("VERBOSE_STARTUP") == "1":
                print(f"[OK] CLOUDINARY_URL parseada correctamente. CLOUD_NAME={cfg.cloud_name}. API_KEY={masked_key}")
                print(f"[OK] DEFAULT_FILE_STORAGE set to {DEFAULT_FILE_STORAGE}")
        except (ValueError, AttributeError, TypeError) as e:
            print("[ERROR] Error al configurar cloudinary:", str(e))
            CLOUDINARY_STORAGE = {}
    else:
        msg = "CLOUDINARY_URL malformada. Use: cloudinary://<api_key>:<api_secret>@<cloud_name>"
        if DEBUG:
            print(f"[WARN] {msg} Falling back to local FileSystemStorage because DEBUG=True.")
            DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
            MEDIA_URL = '/media/'
        else:
            raise RuntimeError(msg)
else:
    msg = (
        "CLOUDINARY_URL not set. Configure an environment variable: "
        "CLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<cloud_name>"
    )
    if DEBUG:
        # En desarrollo permitimos fallback local, pero lo notificamos claramente
        print("[WARN] " + msg + " Falling back to local FileSystemStorage because DEBUG=True.")
        DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
        MEDIA_URL = '/media/'
    else:
        # En producción debe existir CLOUDINARY_URL: fallar rápido para ver el error en deploy
        raise RuntimeError(msg)

MEDIA_ROOT = BASE_DIR / 'media'